### ISSUE TITLE
Write Sections Q&As for SO4T

### ISSUE THREAD

**Issue by klemay** [hypothesis/support#123]
Our support team is a bit fuzzy on how "converting" a customer to Sections works - we need a post in SO4T that outlines how this feature works and how to support schools that have been using non-Sections installs and want to upgrade.

This task will be led by Support but will require developer input to make sure technical details are correct.

**Comment by seanh** [comment]
I've added a canvas-sections tag to SO4T with some initial answers to questions that were asked in Slack: https://stackoverflow.com/c/hypothesis/questions/tagged/113

It's perfectly possible to create an SO4T "question" that isn't really a question. You could enter **Sections Guide** as the question title, and then write a guide in the question body and leave the "question" unanswered. For example here's the Stack Overflow folks themselves using a "question" to make a product announcement (and people using the "answers" as comments): <https://meta.stackoverflow.com/questions/354217/sunsetting-documentation>. I think this is a perfectly valid thing to do.

**But** if we do have specific questions about sections I think they would probably be better posted as individual Q&A's rather than as a guide. We can then group them all together under the canvas-sections tag or, once our upgrade request goes through and we get the Collections feature, we can make a "Sections Guide" collection and add the questions to it.

**Comment by klemay** [comment]
@seanh thanks so much - I agree it makes sense for there to be a series of Q&As rather than one guide - changing the name of this issue accordingly.

for now I'm going to keep this issue open and move it into the upcoming sprint, as Support might have follow-on questions for developers and I want to reflect that some developer time may be spent helping / confirming things with Support.
