### ISSUE TITLE
Creating a share link on debezium.io appends "www." to the via proxy URL

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/support#150]
**Describe the bug**
Creating a link through the **share** feature of H to a page or specific annotation on https://debezium.io generates a URL that appends "www." before "debezium.io". Users who try to follow a share link and do not have the browser extension will be presented with an error message.

URL in browser address bar: https://debezium.io/documentation/reference/connectors/mysql.html
URL generated by H **share** button: https://hyp.is/go?url=https%3A%2F%2Fwww.debezium.io%2Fdocumentation%2Freference%2Fconnectors%2Fmysql.html&group=__world__

Note: In the case of this site, trying to load a page through Via pointing to www.debezium.io results in the following error:
>Pywb Error
>Could not load the url from the live web: https://www.debezium.io

Which may warrant its own issue by itself. Removing the "www." from the path in URL allows page to load without error:
https://hyp.is/go?url=https%3A%2F%2Fdebezium.io%2Fdocumentation%2Freference%2Fconnectors%2Fmysql.html&group=__world__

**To Reproduce**
1. Go to https://debezium.io/documentation/reference/connectors/mysql.html
2. Click on the **share** icon to generate a URL for sharing annotations
3. Note that the share URL path now includes "www." in front of debezium.io:
`https://hyp.is/go?url=https%3A%2F%2Fwww.debezium.io%2Fdocumentation%2Freference%2Fconnectors%2Fmysql.html&group=__world__`

**Expected behavior**
The path to the original site embedded in the Via URL should match the original URL of the site loaded in the browser.

**Screenshots**

![Screen Shot 2020-10-13 at 11 29 00 AM](https://user-images.githubusercontent.com/71603629/95892266-44588d00-0d54-11eb-870d-d8596778be2c.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browsers: Chrome 86, Firefox 81

**Additional context**
Have tried to replicate in another site that uses root domain with no "www" subdomain: https://boingboing.net
Here the share feature generates the link without appending "www." as expected.

**Comment by lyzadanger** [comment]
We will respect canonical URLs explicitly claimed; they have this tag in the page:

```
<link rel="canonical" href="https://www.debezium.io/documentation/reference/connectors/mysql.html">
```

That is, _they_ are claiming that the URL for this document has a `www` and we're merely obeying.

**Comment by klemay** [comment]
@mattdricker in order for this to be "fixed" from the user perspective, we would need for the site owner at debezium.io to change that canonical URL to:

`<link rel="canonical" href="https://debezium.io/documentation/reference/connectors/mysql.html">`

Usually in these cases we offer to reach out on behalf of the user if there is an easy way to contact the site owner listed on the site itself, and we encourage the user to reach out separately (since it's a simple change, hearing from more than 1 person might prompt the site owner to swiftly make the change). Let me know if you would like a set of eyes on a draft email either to the user or to the site owner at debezium.io - happy to help with either! 

I am going to close this issue, as there is nothing to be done from a development standpoint on our end.
