### ISSUE TITLE
LMS user building URL assignment gets "Couldn't get the file from Canvas" error

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#162]
**Describe the bug**
A user is creating a URL assignment from https://www.lemonde.fr/planete/article/2020/11/18/le-gouvernement-prepare-un-deconfinement-progressif_6060203_3244.html in a Canvas Sandbox. From what I can tell this is a Course group, not a Section group. When the user launches the assignment they get the "Couldn't get the file from Canvas" error, even this this is not a Canvas Files assignment. We can **not** replicate this in other Sandboxes within that institution, but we weren't able to figure out the difference between this Sandbox and other institutional Sandboxes either.

**To Reproduce**
We can not reproduce this ourselves, but here's a video of the user reproducing the issue: https://drive.google.com/file/d/1L0NF4SEifab2gulnYnthRfHcWSSU1iCk/view?usp=sharing

Other Le Monde articles seem to produce the same issue.

**Expected behavior**
We would not expect to see the Files error on a URL assignment.

**Screenshots**
![image](https://user-images.githubusercontent.com/22603275/101197030-9076ce00-362f-11eb-8c26-465a1199d870.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14
- Chrome 86

**Additional context**
We grabbed the HAR archive from the user: https://drive.google.com/file/d/1oU4gMfF3tuPFVLrO_WuvdVoAHMECeyFB/view?usp=sharing

**Comment by mkdir-washington-edu** [comment]
ticket: https://app.hubspot.com/contacts/6291320/ticket/254378127/

**Comment by mattdricker** [comment]
To summarize what we've learned so far through conversations and tickets (confirmed in parentheses):

- Error shows whether creating module or assignment (Rutgers)
- Error shows whether PDF from Canvas Files, Google Drive, or URL (Rutgers, Wake Forest, Xavier)
- Only one admin level install of H, no course level install (Rutgers)
- Error also shows in newly created, non copied course (Rutgers, Wake Forest)

I have also confirmed in a previous call with LMS admin at Xavier the proper admin install, with all scoping and API endpoints we specify included.

**Comment by seanh** [comment]
What's a Canvas Sandbox? We've never heard of those before.

**Comment by seanh** [comment]
You can see from the <samp>Error Details</samp> when the user opens them that we're getting a `401 Unauthorized`, `Insufficient scopes on access token` error from Canvas

**Comment by seanh** [comment]
The fact that the error shows when creating URL assignments (and not just Canvas Files ones) suggests that the error response we're getting from the Canvas API is from the sections API not the files API, and we're showing the wrong error message for some reason

**Comment by seanh** [comment]
One thing I'm noticing is that our code seems to think that if we receive a `401` error from Canvas that means that:

> ... the user's access token is fine but they don't have permission to carry out the requested action. For example a user might not have permission to get a public URL for a file if they don't have permission to read that file.

But in fact I can see from the `401 Unauthorized`, `Insufficient scopes on access token` error from the user's video that Canvas also uses `401` when the user's access token is _not_ fine, when the access token has insufficient scopes.

**Comment by seanh** [comment]
Trying to figure out how to reproduce this "insufficient scopes on access token" error from the Canvas API...

**Comment by seanh** [comment]
Whenever I remove some of the necessary scopes from the developer key (e.g. if I remove the sections scopes) our app forcing a re-authorization (popup window) and then shows our "Developer key scopes missing" error.

**Comment by seanh** [comment]
What I've been doing locally is:

* Add all the correct scopes to the developer key
* Launch an HTML assignment (our app will show the authorization popup window and get an access token)
* Now remove one of the necessary sections scopes from the key
* Launch the HTML assignment again

This causes our app to try to call Canvas's sections API with an access token from a developer key that no longer has the sections scopes. When it does this it gets `401` error with: `{"errors":[{"message":"Invalid access token."}]}` from the Canvas API. I think the access token is "invalid" because when you change the developer key's scopes in Canvas that invalidates all the access tokens that've already been given out from that developer key.

So I'm _not_ getting the `401` error with `Insufficient scopes on access token` that the user is getting...

**Comment by seanh** [comment]
I've managed to reproduce the behaviour from the user's video locally like this:

1. The developer key _does_ have all the necessary scopes, including the sections scopes
2. I hacked our app to _not_ request the sections scopes on the access token, even though it should do
3. Launched an HTML assignment in a course that uses sections

This gets the `401 Unauthorized`, `Insufficient scopes on access token` error from the Canvas API and triggers the **Couldn't get the file from Canvas** error dialog even though I'm launching an HTML assignment. If I click the <kbd>Try again</kbd> it launches the assignment but the client loads forever as in the user's video.

The question is how is this happening to users, since I had to break the code to reproduce it locally?

Somehow we've requested an access token without the sections scopes on it, even though the course _does_ have sections enabled.

**Comment by seanh** [comment]
Might have something to do with the logic here for deciding whether to ask for the sections scopes or not when getting an access token: https://github.com/hypothesis/lms/blob/25d7bb5385aec8a29906da624535fd5a116d93a3/lms/views/api/canvas/authorize.py#L41-L49

Or the problem might just be what we're mistaking the `Insufficient scopes on access token` error for a Canvas Files error.

**Comment by seanh** [comment]
I've deployed a "fix" for this, hopefully now:

1. When the users launch the assignments they'll still see the **Canvas file not found** error
2. But now when they click <kbd>Try again</kbd> it should work
3. You should only have to click <kbd>Try again</kbd> once, after that re-launching the assignment or launching another assignment should just work

Of course it makes no sense for the **Canvas file not found** to show when not even launching a Canvas files assignment, but at least users should now be able to get past the problem

**Comment by seanh** [comment]
The users should no longer see the non-sensical **Canvas file not found** error in this case, either
