### ISSUE TITLE
LMS Files: long file names have the left side of the file name extend outside the view of the user

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#219]
**Describe the bug**
When a PDF with a long file name is uploaded to the BB Files collection and an instructor uses the BB Files integration to view available PDFs ([instructions here](https://web.hypothes.is/help/using-hypothesis-with-blackboard-course-files/)), it seems like the window that views the files can't handle long file names and is right- or center-justified.

<img width="766" alt="Screen Shot 2021-08-27 at 11 07 28 AM" src="https://user-images.githubusercontent.com/22603275/131150210-50286627-1c3c-4a59-b144-27d8e59738f8.png">

**To Reproduce**
1. Follow the directions to add a PDF to the course Content collection
2. Use a file with a name like "What do we mean when we say, “Transformative learning experiences powered by technology”_ _ by Office of Ed Tech _ Medium.pdf"
3. Create a new BB assignment and select the BB Files option

**Expected behavior**
I think file names that extend beyond the window are fine if they are left-justified. We may also want to wrap long file names instead.

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - Chrome 92

**Comment by lyzadanger** [comment]
@mkdir-washington-edu This ticket wasn't in the sprint and wasn't in a place I normally "look," so I had heard a rumor about it but never saw it directly. In any case, changes shipped as of https://github.com/hypothesis/lms/pull/3084 should make this better: long filenames are now elided with an ellipsis (`...`) and aren't "weird" like in the screengrab anymore.

_If you would prefer_ that long filenames wrap to a second line instead of being truncated (doesn't look quite as elegant but isn't a disaster, either), that is a trivial change and I'd be glad to make it. Just let me know.

**Comment by mkdir-washington-edu** [comment]
From our conversation today, some users (especially those using the fingerprinting tool) have needed information at the end of the the file name, so a solution that wraps the file name so they can see the beginning and end of the file name is probably the best solution.
