### ISSUE TITLE
Uncaught TypeError in Canvas PDF assignment

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#98]
**Describe the bug**
In a Google Picker assignment in our Canvas installation, we get an Uncaught TypeError. 
![image](https://user-images.githubusercontent.com/22603275/77672124-e0f54200-6f5e-11ea-9df6-470899d6dde5.png)
(expanded error below)

**To Reproduce**
1. Log into hypothesis.instructure.com using the "Teacher account" here: https://docs.google.com/document/d/1Nl-ytl92Ydg-Z-1oQjUQUW_tt_AIVxXctrYXMD1Eqzs/edit?usp=sharing
2. Go to https://hypothesis.instructure.com/courses/92/assignments/768
3. Open the Console in Dev Tools

**Expanded error**
![image](https://user-images.githubusercontent.com/22603275/77672397-3f222500-6f5f-11ea-90ff-4e2618bc0389.png)
![image](https://user-images.githubusercontent.com/22603275/77672417-447f6f80-6f5f-11ea-9c06-bd4f44676407.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Chrome 80

**Additional context**
https://hypothes-is.slack.com/archives/C2BLQDKHA/p1585238746026800

**Comment by LMS007** [comment]
The initial JS error has been fixed with PR https://github.com/hypothesis/lms/commit/5e198f816ce4f64fc7bd1dcc4df508e7541e115d

It was affecting all LMS assignments. 

There is still a lingering 403 error with the example in this ticket where google drive is not allowing via3 to access the file. That is an unrelated issue.
